version: '3'

services:
  java8221:
    build:
      context: ./alpine-jre1.8.0_221/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-java:1.8.221
    container_name: alpine-java
  
  java8251:
    build:
      context: ./alpine-jre1.8.0_251/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-java:1.8.251
    container_name: alpine-java

  dragonwell:
    build:
      context: ./alpine-jre-dragonwell_8.6.6/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-java:dragonwell-8.6.6
    container_name: alpine-java

  corretto8:
    build:
      context: ./alpine-jre-corretto_8u292/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-java:1.8.292
    container_name: alpine-java

  corretto11:
    build:
      context: ./alpine-jre-corretto_11/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-java:1.11.1191
    container_name: alpine-java

  rtmp:
    build:
      context: ./alpine-nginx-rtmp/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-nginx:rtmp_1.18.0
    container_name: alpine-rtmp

  nginx:
    build:
      context: ./alpine-nginx1.18.0/
      dockerfile: ./Dockerfile
    image: pnoker/alpine-nginx:1.18.0
    container_name: alpine-nginx
